name       : quassel
version    : 0.12.5
release    : 9
source     :
    - http://quassel-irc.org/pub/quassel-0.12.5.tar.bz2 : 1894574dfd79654152a5b7427e7df592b055ae908230504f98a4cb48961e74e2
license    :
    - GPL-2.0-only
    - GPL-3.0-only
component  : network.irc
summary    : Quassel IRC is a modern, cross-platform, distributed IRC client.
description: |
    Quassel IRC is a modern, cross-platform, distributed IRC client.
builddeps  :
    - pkgconfig(dbusmenu-qt5)
    - pkgconfig(gl)
    - pkgconfig(phonon4qt5)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5WebEngine)
    - extra-cmake-modules
    - sonnet-devel
setup      : |
    %patch -p1 < $pkgfiles/qt5_use_modules.patch
    %cmake_ninja \
        -DHAVE_SSL=ON \
        -DUSE_QT5=ON \
        -DWANT_CORE=OFF \
        -DWANT_MONO=ON \
        -DWITH_KDE=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
