name       : quassel
version    : 0.12.4
release    : 5
source     :
    - http://quassel-irc.org/pub/quassel-0.12.4.tar.bz2 : 93e4e54cb3743cbe2e5684c2fcba94fd2bc2cd739f7672dee14341b49c29444d
license    : GPL-2.0
component  : network.irc
summary    : Quassel IRC is a modern, cross-platform, distributed IRC client.
description: |
    Quassel IRC is a modern, cross-platform, distributed IRC client.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5WebKit)
setup      : |
    %cmake \
        -DHAVE_SSL=ON \
        -DUSE_QT5=ON \
        -DWANT_CORE=OFF \
        -DWANT_MONO=ON \
        -DWITH_DBUS=ON \
        -DWITH_KDE=OFF \
        -DWITH=WEBKIT=ON
build      : |
    %make
install    : |
    %make_install
