name       : quassel
version    : 0.13.0
release    : 10
source     :
    - https://quassel-irc.org/pub/quassel-0.13.0.tar.bz2 : d9822002de5bb1fd1002cccd537e5a0bc8ec365d355fdff4fb7818daefade976
license    : GPL-2.0-or-later
component  : network.irc
summary    : Quassel IRC is a modern, cross-platform, distributed IRC client
description: |
    Quassel IRC is a modern, cross-platform, distributed IRC client, meaning that one (or multiple) client(s) can attach to and detach from a central core -- much like the popular combination of screen and a text-based IRC client such as WeeChat, but graphical.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(dbusmenu-qt5)
    - pkgconfig(phonon4qt5)
    - pkgconfig(qca2-qt5)
    - extra-cmake-modules
    - sonnet-devel
rundeps    :
    - breeze-icons
setup      : |
    %patch -p1 < $pkgfiles/qt5_use_modules.patch
    %cmake_ninja \
        -DHAVE_SSL=ON \
        -DUSE_QT5=ON \
        -DWANT_CORE=OFF \
        -DWANT_MONO=ON \
        -DWITH_KDE=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
