name       : quassel
version    : 0.14.0
release    : 13
source     :
    - https://github.com/quassel/quassel/releases/download/0.14.0/quassel-0.14.0.tar.xz : 090777f37a6ae1057a046d5c2896ce5e4bef2382377e3ba52c63efe6b5fe4e10
license    : GPL-2.0-or-later
component  : network.irc
summary    : Quassel IRC is a modern, cross-platform, distributed IRC client
description: |
    Quassel IRC is a modern, cross-platform, distributed IRC client, meaning that one (or multiple) client(s) can attach to and detach from a central core -- much like the popular combination of screen and a text-based IRC client such as WeeChat, but graphical.
builddeps  :
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(dbusmenu-qt5)
    - pkgconfig(qca2-qt5)
    - libboost-devel
    - sonnet-devel
rundeps    :
    - breeze-icons
setup      : |
    %cmake_ninja \
        -DHAVE_SSL=ON \
        -DUSE_QT5=ON \
        -DWANT_CORE=OFF \
        -DWANT_MONO=ON \
        -DWITH_KDE=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
